In [ ]:
!pip install ijson==3.2.1

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 113.1/113.1 kB 2.9 MB/s eta 0:00:00


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import ijson
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import json

In [ ]:
def load_files_to_dfs(folder_path):
    # List to store the dataframes
    honda_dfs = []

    # Get all folders (assuming they are numbered and in the folder_path)
    for folder in os.listdir(folder_path):
        folder_num = folder  # Folder name (assuming it is the number)
        folder_full_path = os.path.join(folder_path, folder)

        if os.path.isdir(folder_full_path):
            # Look specifically for the 'xsens.csv' and 'labels.csv' file in each folder
            file_path_xsens = os.path.join(folder_full_path, 'xsens.csv')
            file_path_labels = os.path.join(folder_full_path, 'labels.csv')

            # making sure both paths exist prior to uploading df
            if os.path.exists(file_path_xsens):
                if os.path.exists(file_path_labels):
                    # Load the files into a DataFrames (assuming csv format)
                    df_xsens = pd.read_csv(file_path_xsens)
                    df_labels = pd.read_csv(file_path_labels)

                    # Merge the two DataFrames on the 'time', 'participant_id', 'task' column
                    df = pd.merge(df_xsens, df_labels, on=['time', 'participant_id', 'task'])

                    # Add participant_num column
                    df['participant_num'] = folder_num
                    print(folder_num)

                    # Add the DataFrame to the list
                    honda_dfs.append(df)

    return honda_dfs

# Usage example
folder_path = '/content/drive/MyDrive/Next_Step/Honda: multi_modal_gait_database/data_set/courseB'  # Replace with the path to the main directory containing folders
dataframes = load_files_to_dfs(folder_path)

# # Print the dataframes list
# for idx, df in enumerate(dataframes):
#     print(f"DataFrame from folder {idx + 1}:\n", df.head())


id15
id01
id12
id14
id24
id23
id08
id25
id22
id19
id02
id04
id10
id16
id18
id17
id05
id13
id03


In [ ]:
len(dataframes)

20

In [ ]:
dataframes_copy = dataframes

In [ ]:
# list(dataframes_copy[0].columns)

In [ ]:
dataframes[0]['walk_mode'].unique()

array(['walk', 'slope_down', 'slope_up', 'stairs_up'], dtype=object)

In [ ]:
sensor_types = ['orientation','position','velocity','acceleration','angularVelocity','angularAcceleration','sensorFreeAcceleration','sensorMagneticField','sensorOrientation','jointAngle','jointAngleXZY']

sensor_locations = ['Pelvis', 'L5', 'L3', 'T12', 'T8', 'Neck', 'Head', 'RightShoulder', 'RightUpperArm', 'RightForeArm', 'RightHand', 'LeftShoulder', 'LeftUpperArm', 'LeftForeArm', 'LeftHand', 'RightUpperLeg', 'RightLowerLeg',
                    'RightFoot', 'RightToe', 'LeftUpperLeg', 'LeftLowerLeg', 'LeftFoot', 'LeftToe']

axes = ['x', 'y', 'z', 'ql', 'qi', 'qj', 'qk']

columns = ['walk_mode', 'time', 'participant_id', 'task', 'sensor_location', 'orientation_q1', 'orientation_qi', 'orientation_qj', 'orientation_qk',
           'position_x', 'position_y', 'position_z', 'velocity_x', 'velocity_y', 'velocity_z', 'acceleration_x', 'acceleration_y', 'acceleration_z',
           'angularVelocity_x', 'angularVelocity_y', 'angularVelocity_z', 'angularAcceleration_x', 'angularAcceleration_y', 'angularAcceleration_z',
           'sensorFreeAcceleration_x', 'sensorFreeAcceleration_y', 'sensorFreeAcceleration_z', 'sensorMagneticField_x', 'sensorMagneticField_y',
           'sensorMagneticField_z', 'sensorOrientation_q1', 'sensorOrientation_qi', 'sensorOrientation_qj', 'sensorOrientation_qk', 'jointAngle_x',
           'jointAngle_y', 'jointAngle_z', 'jointAngleXZY_x', 'jointAngleXZY_y', 'jointAngleXZY_z']


In [ ]:
new_column_names = {
    'index': 'index',
    'orientation_q1': 'OriInc_q0',                      # omit in future
    'orientation_qi': 'OriInc_q1',                      # omit in future
    'orientation_qj': 'OriInc_q2',                      # omit in future
    'orientation_qk': 'OriInc_q3',                      # omit in future
    'sensor_location': 'sensor_location',
    'position_x': 'Position_X',                         # omit in future
    'position_y': 'Position_Y',                         # omit in future
    'position_z': 'Position_Z',                         # omit in future
    'velocity_x': 'VelInc_X',                           # omit in future
    'velocity_y': 'VelInc_Y',                           # omit in future
    'velocity_z': 'VelInc_Z',                           # omit in future
    'acceleration_x': 'Acc_X',
    'acceleration_y': 'Acc_Y',
    'acceleration_z': 'Acc_Z',
    'angularVelocity_x': 'Gyr_X',
    'angularVelocity_y': 'Gyr_Y',
    'angularVelocity_z': 'Gyr_Z',
    'angularAcceleration_x': 'AngularAcceleration_X',   # omit in future
    'angularAcceleration_y': 'AngularAcceleration_Y',   # omit in future
    'angularAcceleration_z': 'AngularAcceleration_Z',   # omit in future
    'sensorFreeAcceleration_x': 'FreeAcc_X',
    'sensorFreeAcceleration_y': 'FreeAcc_Y',
    'sensorFreeAcceleration_z': 'FreeAcc_Z',
    'sensorMagneticField_x': 'Mag_X',
    'sensorMagneticField_y': 'Mag_Y',
    'sensorMagneticField_z': 'Mag_Z',
    'sensorOrientation_q1': 'sensorOrientation_q1',     # omit in future
    'sensorOrientation_qi': 'sensorOrientation_qi',     # omit in future
    'sensorOrientation_qj': 'sensorOrientation_qj',     # omit in future
    'sensorOrientation_qk': 'sensorOrientation_qk',     # omit in future
    'jointAngle_x': 'JointAngle_X',                     # omit in future
    'jointAngle_y': 'JointAngle_Y',                     # omit in future
    'jointAngle_z': 'JointAngle_Z',                     # omit in future
    'jointAngleXZY_x': 'Roll',                          # omit in future
    'jointAngleXZY_y': 'Pitch',                         # omit in future
    'jointAngleXZY_z': 'Yaw'                            # omit in future
}

In [ ]:
# get the 5 types of surfaces/actions done in this dataset
walk_modes = dataframes_copy[0]['walk_mode'].unique()

# create a subset dataframe for each of the types
subset_dfs = {}
for walk_mode in walk_modes:
  for df in dataframes_copy:
      identifier = walk_mode + '_' + df['participant_num'].iloc[0]
      if identifier not in subset_dfs:
          subset_dfs[identifier] = df[df['walk_mode'] == walk_mode]


In [ ]:
# subset_dfs.keys()

In [ ]:
subset_dfs['slope_up_id12']

,time,participant_id,task,orientation_Pelvis_q1,orientation_Pelvis_qi,orientation_Pelvis_qj,orientation_Pelvis_qk,orientation_L5_q1,orientation_L5_qi,orientation_L5_qj,...,insoles_RightFoot_time_to_lift,xsens_footContacts_LeftFoot_Heel,xsens_footContacts_LeftFoot_Toe,xsens_footContacts_RightFoot_Heel,xsens_footContacts_RightFoot_Toe,walk_orientation,walk_interaction,walk_mode_id,walk_orientation_id,participant_num
3369,56150,12,B,-0.997874,-0.015332,-0.004589,0.063177,-0.994699,-0.012586,-0.026812,...,633.0,False,False,True,False,curve_left,no,3,6,id12
3370,56167,12,B,-0.997711,-0.003879,-0.003003,0.067449,-0.994729,-0.006569,-0.024187,...,616.0,False,False,True,False,curve_left,no,3,6,id12
3371,56183,12,B,-0.997551,0.007205,-0.001577,0.069558,-0.994843,-0.000658,-0.022280,...,600.0,False,False,True,False,curve_left,no,3,6,id12
3372,56200,12,B,-0.997422,0.015958,-0.000924,0.069950,-0.995018,0.004017,-0.021477,...,583.0,False,False,True,False,curve_left,no,3,6,id12
3373,56217,12,B,-0.997367,0.021087,0.000059,0.069392,-0.995250,0.006587,-0.020977,...,566.0,False,False,True,False,curve_left,no,3,6,id12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30948,515800,12,B,-0.997126,-0.011914,-0.000285,-0.074821,-0.993817,-0.009327,-0.035550,...,217.0,False,False,False,False,turn_around_clockwise,no,3,8,id12
30949,515817,12,B,-0.997331,-0.014365,-0.000540,-0.071590,-0.994009,-0.011500,-0.035017,...,200.0,False,False,False,False,turn_around_clockwise,no,3,8,id12
30950,515833,12,B,-0.997635,-0.016925,-0.003531,-0.066519,-0.994261,-0.013871,-0.035524,...,184.0,True,False,False,False,turn_around_clockwise,no,3,8,id12
30951,515850,12,B,-0.998140,-0.019433,-0.004947,-0.057572,-0.994757,-0.016214,-0.034882,...,167.0,True,False,False,False,turn_around_clockwise,no,3,8,id12


In [ ]:
import pandas as pd

# Define your list of sensor locations
sensor_locations = ['Pelvis', 'L5', 'L3', 'T12', 'T8', 'Neck', 'Head', 'RightShoulder', 'RightUpperArm', 'RightForeArm', 'RightHand',
                    'LeftShoulder', 'LeftUpperArm', 'LeftForeArm', 'LeftHand', 'RightUpperLeg', 'RightLowerLeg', 'RightFoot',
                    'RightToe', 'LeftUpperLeg', 'LeftLowerLeg', 'LeftFoot', 'LeftToe']

# Function to extract the sensor location from a column name based on the sensor_locations list
def extract_sensor_location(column_name):
    for location in sensor_locations:
        if location in column_name:
            return location
    return None

# Function to remove the sensor location from a column name
def remove_sensor_location(column_name):
    for location in sensor_locations:
        if location in column_name:
            # Remove the sensor location from the column name
            return column_name.replace(location, '').strip('_')
    return column_name

# Loop over each DataFrame in subset_dfs (assuming it's a dictionary of trial DataFrames)
for key, trial_df in subset_dfs.items():
    df_list = []
    surface_type = key.split('_')
    if len(surface_type) > 2:
        surface_type = ' '.join(surface_type[:2])
    else:
        surface_type = surface_type[0]

    # For each sensor, collect relevant columns and create a new DataFrame
    for sensor_location in sensor_locations:
        # Find all columns related to this sensor location
        sensor_columns = [col for col in trial_df.columns if sensor_location in col]

        if sensor_columns:
            # Create a new DataFrame for this sensor
            df_by_sensor = pd.DataFrame({
                "time": trial_df["time"],
                "participant_id": trial_df["participant_id"],
                "task": trial_df["task"],
                "surface_type": surface_type,  # Use the derived surface type
                "sensor_location": sensor_location
            })

            # For each sensor-related column, add it to the new DataFrame
            for col in sensor_columns:
                # Remove sensor location from the column name for readability
                new_column_name = remove_sensor_location(col)
                df_by_sensor[new_column_name] = trial_df[col]

            # Append the sensor DataFrame to the list
            df_list.append(df_by_sensor)

    # Concatenate all DataFrames for this trial, if any were created
    if df_list:
        df = pd.concat(df_list)

        # Export df to CSV
        df.to_csv(f'/content/drive/MyDrive/Next_Step/Honda_Participants/CourseB/{key}.csv', index=False)

        # Clear the local memory
        # del df_list
        # del df

        print(f"Processed {key}")
    else:
        print(f"No valid sensor columns to process for {key}")


Processed walk_id15
Processed walk_id01
Processed walk_id12
Processed walk_id14
Processed walk_id24
Processed walk_id23
Processed walk_id08
Processed walk_id07
Processed walk_id25
Processed walk_id22
Processed walk_id19
Processed walk_id02
Processed walk_id04
Processed walk_id10
Processed walk_id16
Processed walk_id18
Processed walk_id05
Processed walk_id13
Processed walk_id03
Processed slope_down_id15
Processed slope_down_id01
Processed slope_down_id12
Processed slope_down_id14
Processed slope_down_id24
Processed slope_down_id23
Processed slope_down_id08
Processed slope_down_id07
Processed slope_down_id25
Processed slope_down_id22
Processed slope_down_id19
Processed slope_down_id02
Processed slope_down_id04
Processed slope_down_id10
Processed slope_down_id16
Processed slope_down_id18
Processed slope_down_id17
Processed slope_down_id05
Processed slope_down_id13
Processed slope_down_id03
Processed slope_up_id15
Processed slope_up_id01
Processed slope_up_id12
Processed slope_up_id14
Proc

In [ ]:
# # this is all the data for participant 1 from course A
# ['slope_down_id01']
# ['walk_id01']
# ['slope_up_id01']
# ['stairs_down_id01']
# ['stairs_up_id01']

In [ ]:
subset_dfs.keys()

dict_keys(['walk_id15', 'walk_id01', 'walk_id12', 'walk_id14', 'walk_id24', 'walk_id23', 'walk_id08', 'walk_id07', 'walk_id25', 'walk_id22', 'walk_id19', 'walk_id02', 'walk_id04', 'walk_id10', 'walk_id16', 'walk_id18', 'walk_id17', 'walk_id05', 'walk_id13', 'walk_id03', 'slope_down_id15', 'slope_down_id01', 'slope_down_id12', 'slope_down_id14', 'slope_down_id24', 'slope_down_id23', 'slope_down_id08', 'slope_down_id07', 'slope_down_id25', 'slope_down_id22', 'slope_down_id19', 'slope_down_id02', 'slope_down_id04', 'slope_down_id10', 'slope_down_id16', 'slope_down_id18', 'slope_down_id17', 'slope_down_id05', 'slope_down_id13', 'slope_down_id03', 'slope_up_id15', 'slope_up_id01', 'slope_up_id12', 'slope_up_id14', 'slope_up_id24', 'slope_up_id23', 'slope_up_id08', 'slope_up_id07', 'slope_up_id25', 'slope_up_id22', 'slope_up_id19', 'slope_up_id02', 'slope_up_id04', 'slope_up_id10', 'slope_up_id16', 'slope_up_id18', 'slope_up_id17', 'slope_up_id05', 'slope_up_id13', 'slope_up_id03', 'stairs_u

In [ ]:
import os
import shutil

# Iterate over subset_dfs items
for key, value in subset_dfs.items():
    # Extract participant ID
    participant = key.split('_')[-1]
    participant_number = participant[-2:]

    # Define the directory for this participant
    participant_dir = f'/content/drive/MyDrive/Next_Step/Honda_Participants/CourseB/Participant_{participant_number}'

    # Create the participant folder if it doesn't exist
    os.makedirs(participant_dir, exist_ok=True)

    # Define the source CSV file path
    source_file = f'/content/drive/MyDrive/Next_Step/Honda_Participants/CourseB/{key}.csv'

    # Define the destination file path in the participant's folder
    destination_file = os.path.join(participant_dir, f'{key}.csv')

    # Move the file if it exists
    if os.path.exists(source_file):
        shutil.move(source_file, destination_file)
        print(f"Moved {source_file} to {destination_file}")
    else:
        print(f"{source_file} does not exist")


Moved /content/drive/MyDrive/Next_Step/Honda_Participants/CourseB/walk_id15.csv to /content/drive/MyDrive/Next_Step/Honda_Participants/CourseB/Participant_15/walk_id15.csv
Moved /content/drive/MyDrive/Next_Step/Honda_Participants/CourseB/walk_id01.csv to /content/drive/MyDrive/Next_Step/Honda_Participants/CourseB/Participant_01/walk_id01.csv
Moved /content/drive/MyDrive/Next_Step/Honda_Participants/CourseB/walk_id12.csv to /content/drive/MyDrive/Next_Step/Honda_Participants/CourseB/Participant_12/walk_id12.csv
Moved /content/drive/MyDrive/Next_Step/Honda_Participants/CourseB/walk_id14.csv to /content/drive/MyDrive/Next_Step/Honda_Participants/CourseB/Participant_14/walk_id14.csv
Moved /content/drive/MyDrive/Next_Step/Honda_Participants/CourseB/walk_id24.csv to /content/drive/MyDrive/Next_Step/Honda_Participants/CourseB/Participant_24/walk_id24.csv
Moved /content/drive/MyDrive/Next_Step/Honda_Participants/CourseB/walk_id23.csv to /content/drive/MyDrive/Next_Step/Honda_Participants/Cours

In [ ]:
import os
import pandas as pd
from glob import glob

# Define the folder path containing your subfolders with CSV files
folder_path = '/content/drive/MyDrive/Next_Step/Honda_Participants/CourseB'  # Replace with your actual folder path

# Create an empty dictionary to store the merged DataFrames
merged_df_dict = {}

# Get a list of all subdirectories within the main folder
subfolders = [f.path for f in os.scandir(folder_path) if f.is_dir()]

# Function to merge CSV files in a single subfolder
def merge_csv_files_in_folder(subfolder_path):
    # Get all CSV files in the subfolder
    csv_files = glob(os.path.join(subfolder_path, '*.csv'))

    # If there are CSV files in the folder, read and merge them
    if csv_files:
        # Read each CSV file and store them in a list
        df_list = [pd.read_csv(file, low_memory=False) for file in csv_files]

        # Merge the DataFrames
        merged_df = pd.concat(df_list, ignore_index=True)

        # Extract folder name to create a key for the merged DataFrame
        folder_name = os.path.basename(subfolder_path)

        # Return the merged DataFrame with folder name as the key
        print(f"Merged {len(csv_files)} CSV files in folder: {folder_name}")
        return folder_name, merged_df
    else:
        print(f"No CSV files found in {subfolder_path}")
        return None

for subfolder in subfolders:
    result = merge_csv_files_in_folder(subfolder)
    if result:
        key, merged_df = result
        merged_df_dict[key] = merged_df

for key, df in merged_df_dict.items():
    df.to_csv(f'/content/drive/MyDrive/Next_Step/Honda_Participants/CourseB/{key}_merged.csv', index=False)

print(f"Processed {len(merged_df_dict)} folders and merged their CSV files.")

Merged 4 CSV files in folder: Participant_15
Merged 4 CSV files in folder: Participant_01
Merged 4 CSV files in folder: Participant_12
Merged 4 CSV files in folder: Participant_14
Merged 4 CSV files in folder: Participant_24
Merged 4 CSV files in folder: Participant_23
Merged 4 CSV files in folder: Participant_08
Merged 4 CSV files in folder: Participant_07
Merged 4 CSV files in folder: Participant_25
Merged 4 CSV files in folder: Participant_22
Merged 4 CSV files in folder: Participant_19
Merged 4 CSV files in folder: Participant_02
Merged 4 CSV files in folder: Participant_04
Merged 4 CSV files in folder: Participant_10
Merged 4 CSV files in folder: Participant_16
Merged 4 CSV files in folder: Participant_05
Merged 4 CSV files in folder: Participant_13
Merged 4 CSV files in folder: Participant_03
Merged 2 CSV files in folder: foot_pressure_data


KeyboardInterrupt: 

In [ ]:
import ijson
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import json

In [ ]:
def load_files_to_dfs(folder_path):
    # List to store the dataframes
    honda_dfs = []

    # Get all folders (assuming they are numbered and in the folder_path)
    for folder in os.listdir(folder_path):
        folder_num = folder  # Folder name (assuming it is the number)
        folder_full_path = os.path.join(folder_path, folder)

        if os.path.isdir(folder_full_path):
            # Look specifically for the 'insoles.csv' and 'labels.csv' file in each folder
            file_path_insoles = os.path.join(folder_full_path, 'insoles.csv')
            file_path_labels = os.path.join(folder_full_path, 'labels.csv')

            # making sure both paths exist prior to uploading df
            if os.path.exists(file_path_insoles):
                if os.path.exists(file_path_labels):
                    # Load the files into a DataFrames (assuming csv format)
                    df_insoles = pd.read_csv(file_path_insoles)
                    df_labels = pd.read_csv(file_path_labels)

                    # Merge the two DataFrames on the 'time', 'participant_id', 'task' column
                    df = pd.merge(df_insoles, df_labels, on=['time', 'participant_id', 'task'])

                    # Add participant_num column
                    df['participant_num'] = folder_num
                    print(folder_num)

                    # Add the DataFrame to the list
                    honda_dfs.append(df)

    return honda_dfs

# Usage example
folder_path = '/content/drive/MyDrive/Next_Step/Honda: multi_modal_gait_database/data_set/courseB'  # Replace with the path to the main directory containing folders
dataframes = load_files_to_dfs(folder_path)

# # Print the dataframes list
for idx, df in enumerate(dataframes):
    print(f"DataFrame from folder {idx + 1}:\n", df.head())


id15
id01
id12
id14
id24
id23
id08
id07
id25
id22
id19
id02
id04
id10
id16
id18
id17
id05
id13
id03
DataFrame from folder 1:
    Unnamed: 0  time  participant_id task  Left_Hallux  Left_Toes  Left_Met1  \
0           0     0              15    B          4.0        0.0        6.0   
1           1    16              15    B          1.0        0.0        3.0   
2           2    33              15    B          1.0        1.0        1.0   
3           3    50              15    B          0.0        4.0        1.0   
4           4    66              15    B          5.0        4.0        1.0   

   Left_Met3  Left_Met5  Left_Arch  ...  insoles_RightFoot_time_to_lift  \
0      232.0      315.0      666.0  ...                           866.0   
1      228.0      322.0      666.0  ...                           850.0   
2      233.0      317.0      660.0  ...                           833.0   
3      233.0      313.0      666.0  ...                           816.0   
4      230.0      320.0 

In [ ]:
len(dataframes)

20

In [ ]:
dataframes_copy = dataframes

In [ ]:
#list all the columns
# list(dataframes[0].columns)

In [ ]:
dataframes[0]['walk_mode'].unique()

array(['walk', 'slope_down', 'slope_up', 'stairs_up'], dtype=object)

In [ ]:
dataframes[0]

,Unnamed: 0,time,participant_id,task,Left_Hallux,Left_Toes,Left_Met1,Left_Met3,Left_Met5,Left_Arch,...,insoles_RightFoot_time_to_lift,xsens_footContacts_LeftFoot_Heel,xsens_footContacts_LeftFoot_Toe,xsens_footContacts_RightFoot_Heel,xsens_footContacts_RightFoot_Toe,walk_orientation,walk_interaction,walk_mode_id,walk_orientation_id,participant_num
0,0,0,15,B,4.0,0.0,6.0,232.0,315.0,666.0,...,866.0,False,False,True,False,straight,no,8,1,id15
1,1,16,15,B,1.0,0.0,3.0,228.0,322.0,666.0,...,850.0,False,False,True,False,straight,no,8,1,id15
2,2,33,15,B,1.0,1.0,1.0,233.0,317.0,660.0,...,833.0,False,False,True,False,straight,no,8,1,id15
3,3,50,15,B,0.0,4.0,1.0,233.0,313.0,666.0,...,816.0,False,False,True,False,straight,no,8,1,id15
4,4,66,15,B,5.0,4.0,1.0,230.0,320.0,666.0,...,800.0,False,False,True,False,straight,no,8,1,id15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34755,34755,579250,15,B,307.0,3.0,0.0,271.0,232.0,0.0,...,-1.0,False,False,True,False,straight,no,8,17,id15
34756,34756,579266,15,B,246.0,4.0,1.0,259.0,229.0,2.0,...,-1.0,False,False,True,False,straight,no,8,17,id15
34757,34757,579283,15,B,206.0,1.0,1.0,239.0,139.0,0.0,...,-1.0,False,False,True,False,straight,no,8,17,id15
34758,34758,579300,15,B,1.0,1.0,1.0,139.0,103.0,1.0,...,-1.0,False,False,False,False,straight,no,8,17,id15


In [ ]:
sensor_types = ['Acc','Mag','Gyr']

leg = ['Left', 'Right']

sensor_locations = ['Hallux', 'Toes', 'Met1', 'Met3', 'Met5', 'Arch', 'Heel_R', 'Heel_L']

axes = ['x', 'y', 'z', 'raw', 'norm']

columns = ['Unnamed: 0', 'time', 'participant_id', 'task', 'Left_Hallux', 'Left_Toes', 'Left_Met1',
           'Left_Met3', 'Left_Met5', 'Left_Arch', 'Left_Heel_R', 'Left_Heel_L', 'Left_Acc_x', 'Left_Acc_y', 'Left_Acc_z',
           'Left_Gyr_x', 'Left_Gyr_y', 'Left_Gyr_z', 'Left_Mag_x', 'Left_Mag_y', 'Left_Mag_z', 'Left_Temp', 'Right_Hallux',
           'Right_Toes', 'Right_Met1', 'Right_Met3', 'Right_Met5', 'Right_Arch', 'Right_Heel_L', 'Right_Heel_R', 'Right_Acc_x',
           'Right_Acc_y', 'Right_Acc_z', 'Right_Gyr_x', 'Right_Gyr_y', 'Right_Gyr_z', 'Right_Mag_x', 'Right_Mag_y', 'Right_Mag_z',
           'Right_Temp', 'Right_Toes_raw', 'Right_Hallux_raw', 'Right_Met5_raw', 'Right_Met3_raw', 'Right_Met1_raw', 'Right_Arch_raw', 'Right_Heel_R_raw',
           'Right_Heel_L_raw', 'Left_Toes_raw', 'Left_Hallux_raw', 'Left_Met5_raw', 'Left_Met3_raw', 'Left_Met1_raw', 'Left_Arch_raw', 'Left_Heel_R_raw',
           'Left_Heel_L_raw', 'Right_Acc_x_raw', 'Right_Acc_y_raw', 'Right_Acc_z_raw', 'Right_Mag_x_raw', 'Right_Mag_y_raw', 'Right_Mag_z_raw', 'Right_Gyr_x_raw',
           'Right_Gyr_y_raw', 'Right_Gyr_z_raw', 'Left_Acc_x_raw', 'Left_Acc_y_raw', 'Left_Acc_z_raw', 'Left_Mag_x_raw', 'Left_Mag_z_raw', 'Left_Gyr_x_raw',
           'Left_Gyr_y_raw', 'Left_Gyr_z_raw', 'Left_Hallux_norm', 'Left_Toes_norm', 'Left_Met1_norm', 'Left_Met3_norm', 'Left_Met5_norm', 'Left_Arch_norm',
           'Left_Heel_R_norm', 'Left_Heel_L_norm', 'Right_Hallux_norm', 'Right_Toes_norm', 'Right_Met1_norm', 'Right_Met3_norm', 'Right_Met5_norm', 'Right_Arch_norm',
           'Right_Heel_L_norm', 'Right_Heel_R_norm', 'Left_Max_Pressure_norm', 'Right_Max_Pressure_norm', 'walk_mode', 'repetition', 'insoles_RightFoot_is_step',
           'insoles_LeftFoot_is_step', 'insoles_RightFoot_is_lifted', 'insoles_LeftFoot_is_lifted', 'insoles_LeftFoot_on_ground',
           'insoles_RightFoot_on_ground', 'insoles_LeftFoot_time_to_step', 'insoles_LeftFoot_time_to_lift', 'insoles_RightFoot_time_to_step',
           'insoles_RightFoot_time_to_lift', 'xsens_footContacts_LeftFoot_Heel', 'xsens_footContacts_LeftFoot_Toe', 'xsens_footContacts_RightFoot_Heel',
           'xsens_footContacts_RightFoot_Toe', 'walk_orientation', 'walk_interaction', 'walk_mode_id', 'walk_orientation_id', 'participant_num']


In [ ]:
# get the 5 types of surfaces/actions done in this dataset
walk_modes = dataframes_copy[0]['walk_mode'].unique()

# create a subset dataframe for each of the types
subset_dfs = {}
for walk_mode in walk_modes:
  for df in dataframes_copy:
      identifier = walk_mode + '_' + df['participant_num'].iloc[0]
      if identifier not in subset_dfs:
          subset_dfs[identifier] = df[df['walk_mode'] == walk_mode]


In [ ]:
# change the column names wiht no suffix to have

In [ ]:
# subset_dfs['slope_up_id12']

In [ ]:
extras_df = []

for key, df in subset_dfs.items():
    df.columns = columns
    # keep only listed columns
    df = df[['Unnamed: 0', 'time', 'participant_id', 'task','Left_Max_Pressure_norm', 'Right_Max_Pressure_norm', 'walk_mode', 'repetition', 'insoles_RightFoot_is_step',
           'insoles_LeftFoot_is_step', 'insoles_RightFoot_is_lifted', 'insoles_LeftFoot_is_lifted', 'insoles_LeftFoot_on_ground',
           'insoles_RightFoot_on_ground', 'insoles_LeftFoot_time_to_step', 'insoles_LeftFoot_time_to_lift', 'insoles_RightFoot_time_to_step',
           'insoles_RightFoot_time_to_lift', 'xsens_footContacts_LeftFoot_Heel', 'xsens_footContacts_LeftFoot_Toe', 'xsens_footContacts_RightFoot_Heel',
           'xsens_footContacts_RightFoot_Toe', 'walk_orientation', 'walk_interaction']]

    extras_df.append(df)

# Concatenate all trials into a single DataFrame
all_foot_sensor_extras_df = pd.concat(extras_df, ignore_index=True)

In [ ]:
all_foot_sensor_extras_df

,Unnamed: 0,time,participant_id,task,Left_Max_Pressure_norm,Right_Max_Pressure_norm,walk_mode,repetition,insoles_RightFoot_is_step,insoles_LeftFoot_is_step,...,insoles_LeftFoot_time_to_step,insoles_LeftFoot_time_to_lift,insoles_RightFoot_time_to_step,insoles_RightFoot_time_to_lift,xsens_footContacts_LeftFoot_Heel,xsens_footContacts_LeftFoot_Toe,xsens_footContacts_RightFoot_Heel,xsens_footContacts_RightFoot_Toe,walk_orientation,walk_interaction
0,0,0,15,B,0.804886,0.310507,walk,1,True,True,...,0.0,183.0,0.0,866.0,False,False,True,False,straight,no
1,1,16,15,B,0.748893,0.596743,walk,1,False,False,...,684.0,167.0,1300.0,850.0,False,False,True,False,straight,no
2,2,33,15,B,0.672273,0.675680,walk,1,False,False,...,667.0,150.0,1283.0,833.0,False,False,True,False,straight,no
3,3,50,15,B,0.668793,0.693511,walk,1,False,False,...,650.0,133.0,1266.0,816.0,False,False,True,False,straight,no
4,4,66,15,B,0.652833,0.705888,walk,1,False,False,...,634.0,117.0,1250.0,800.0,False,False,True,False,straight,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
711465,34651,577516,3,B,0.918084,0.151711,stairs_up,3,False,False,...,700.0,167.0,184.0,834.0,False,False,False,False,straight,no
711466,34652,577533,3,B,0.933938,0.121522,stairs_up,3,False,False,...,683.0,150.0,167.0,817.0,False,True,False,False,straight,no
711467,34653,577550,3,B,0.922189,0.145855,stairs_up,3,False,False,...,666.0,133.0,150.0,800.0,False,True,False,False,straight,no
711468,34654,577566,3,B,0.879081,0.193779,stairs_up,3,False,False,...,650.0,117.0,134.0,784.0,False,False,False,False,straight,no


In [ ]:
import pandas as pd

# Define your list of sensor locations
sensor_locations = ['Hallux', 'Toes', 'Met1', 'Met3', 'Met5', 'Arch', 'Heel_R', 'Heel_L']

# Function to extract the sensor location from a column name based on the sensor_locations list
def extract_sensor_location(column_name):
    for location in sensor_locations:
        if location in column_name:
            return location
    return None

# Function to remove the sensor location from a column name
def remove_sensor_location(column_name):
    for location in sensor_locations:
        if location in column_name:
            return column_name.replace(location, '').strip('_')
    return column_name

# Initialize a list to hold DataFrames for all trials
all_trials_df_list = []

# Loop over each DataFrame in subset_dfs (assuming it's a dictionary of trial DataFrames)
for key, trial_df in subset_dfs.items():
    df_list = []
    surface_type = key.split('_')
    if len(surface_type) > 2:
        surface_type = ' '.join(surface_type[:2])
    else:
        surface_type = surface_type[0]

    # For each sensor, collect relevant columns and create a new DataFrame
    for sensor_location in sensor_locations:
        # Find all columns related to this sensor location
        sensor_columns = [col for col in trial_df.columns if sensor_location in col]

        if sensor_columns:
            # Create a new DataFrame for this sensor
            df_by_sensor = pd.DataFrame({
                "time": trial_df["time"],
                "participant_id": trial_df["participant_id"],
                "task": trial_df["task"],
                "surface_type": surface_type,
                "sensor_location": sensor_location
            })

            # For each sensor-related column, add it to the new DataFrame
            for col in sensor_columns:
                new_column_name = remove_sensor_location(col)
                df_by_sensor[new_column_name] = trial_df[col]

            # Append the sensor DataFrame to the list
            df_list.append(df_by_sensor)

    # Concatenate all DataFrames for this trial and add to the main list if any were created
    if df_list:
        trial_df_combined = pd.concat(df_list)
        all_trials_df_list.append(trial_df_combined)

        print(f"Processed {key}")
    else:
        print(f"No valid sensor columns to process for {key}")

# Concatenate all trials into a single DataFrame
all_foot_sensors_df = pd.concat(all_trials_df_list, ignore_index=True)

# Uncomment to export the final combined DataFrame to CSV
# final_combined_df.to_csv('/path/to/final_output.csv', index=False)



Processed walk_id15
Processed walk_id01
Processed walk_id12
Processed walk_id14
Processed walk_id24
Processed walk_id23
Processed walk_id08
Processed walk_id07
Processed walk_id25
Processed walk_id22
Processed walk_id19
Processed walk_id02
Processed walk_id04
Processed walk_id10
Processed walk_id16
Processed walk_id18
Processed walk_id17
Processed walk_id05
Processed walk_id13
Processed walk_id03
Processed slope_down_id15
Processed slope_down_id01
Processed slope_down_id12
Processed slope_down_id14
Processed slope_down_id24
Processed slope_down_id23
Processed slope_down_id08
Processed slope_down_id07
Processed slope_down_id25
Processed slope_down_id22
Processed slope_down_id19
Processed slope_down_id02
Processed slope_down_id04
Processed slope_down_id10
Processed slope_down_id16
Processed slope_down_id18
Processed slope_down_id17
Processed slope_down_id05
Processed slope_down_id13
Processed slope_down_id03
Processed slope_up_id15
Processed slope_up_id01
Processed slope_up_id12
Processe

In [ ]:
foot_sensors_df = all_foot_sensors_df
foot_sensors_extras_df = all_foot_sensor_extras_df

In [ ]:
foot_stepped = foot_sensors_extras_df[(foot_sensors_extras_df['insoles_RightFoot_is_step'] == True) | (foot_sensors_extras_df['insoles_LeftFoot_is_step'] == True)]

In [ ]:
pressure_insole_heelstrikes = foot_stepped['Unnamed: 0']

In [ ]:
# Function to group sequential items
def group_sequential(items):
    grouped = []

    # Check if items is empty
    if not items:
        return grouped  # Return empty list if items is empty

    start = items[0]
    end = items[0]

    for i in range(1, len(items)):
        if items[i] == end + 1:
            end = items[i]
        else:
            grouped.append([start, end])
            start = items[i]
            end = items[i]

    grouped.append([start, end])  # Append the last range
    return grouped


In [ ]:
# foot_sensors_extras_df.head()

In [ ]:
foot_sensors_extras_df['participant_id'].unique()

array([15,  1, 12, 14, 24, 23,  8,  7, 25, 22, 19,  2,  4, 10, 16, 18, 17,
        5, 13,  3])

In [ ]:
heel_strike_insole_segments = []
heel_strike_insole_segments_left = []
heel_strike_xsens_segments = []
heel_strike_xsens_segments_left = []

for p in foot_sensors_extras_df['participant_id'].unique():
    current_ppant_df = foot_sensors_extras_df.loc[foot_sensors_extras_df['participant_id'] == p]

    foot_stepped = current_ppant_df[(current_ppant_df['insoles_RightFoot_is_step'] == True)]
    actual_segments_heel_strike = list(foot_stepped['Unnamed: 0'])
    pairs = np.array([[actual_segments_heel_strike[i], actual_segments_heel_strike[i + 1]] for i in range(len(actual_segments_heel_strike) - 1)])
    heel_strike_insole_segments.append(pairs)

    foot_stepped_left = current_ppant_df[(current_ppant_df['insoles_LeftFoot_is_step'] == True)]
    actual_segments_heel_strike_left = list(foot_stepped_left['Unnamed: 0'])
    pairs_left = np.array([[actual_segments_heel_strike_left[i], actual_segments_heel_strike_left[i + 1]] for i in range(len(actual_segments_heel_strike_left) - 1)])
    heel_strike_insole_segments_left.append(pairs_left)

    xsens_stepped = current_ppant_df[(current_ppant_df['xsens_footContacts_RightFoot_Heel'] == True)]
    xsens_segments_heel_strike = list(xsens_stepped['Unnamed: 0'])
    xsens_grouped_items = np.array(group_sequential(xsens_segments_heel_strike))
    heel_strike_xsens_segments.append(xsens_grouped_items)

    xsens_stepped_left = current_ppant_df[(current_ppant_df['xsens_footContacts_LeftFoot_Heel'] == True)]
    xsens_segments_heel_strike_left = list(xsens_stepped_left['Unnamed: 0'])
    xsens_grouped_items_left = np.array(group_sequential(xsens_segments_heel_strike_left))
    heel_strike_xsens_segments_left.append(xsens_grouped_items_left)



In [ ]:
heel_strike_insole_segments[0]

array([[    0,    79],
       [   79,   154],
       [  154,   230],
       ...,
       [32840, 32904],
       [32904, 32968],
       [32968, 33036]])

In [ ]:
heel_strike_insole_segments_left[0]

array([[    0,    42],
       [   42,   118],
       [  118,   193],
       ...,
       [32810, 32872],
       [32872, 32937],
       [32937, 33003]])

In [ ]:
all_heel_strike_insole_segments_list = []

for p in range(len(heel_strike_insole_segments)):
    # Combine and sort segments from both sides, then get unique values
    all_heel_strike_insole_segments = np.concatenate((heel_strike_insole_segments[p][:, 0], heel_strike_insole_segments_left[p][:, 0]), axis=0)
    all_heel_strike_insole_segments = np.sort(all_heel_strike_insole_segments)
    all_heel_strike_insole_segments = np.unique(all_heel_strike_insole_segments)

    # # Pair up the steps
    # pairs = np.array([[all_heel_strike_insole_segments[i], all_heel_strike_insole_segments[i + 1]]
    #                   for i in range(len(all_heel_strike_insole_segments) - 1)])
    all_heel_strike_insole_segments_list.append(all_heel_strike_insole_segments)



In [ ]:
foot_sensors_df = foot_sensors_df.sort_values(by=["participant_id", "time", "sensor_location"])

In [ ]:
all_foot_sensors_df

,time,participant_id,task,surface_type,sensor_location,Left,Right,Right__raw,Left__raw,Left__norm,Right__norm
0,0,15,B,walk,Hallux,4.0,0.0,4094.584887,3400.962218,0.504274,0.000257
1,16,15,B,walk,Hallux,1.0,4.0,4094.125613,3351.939647,0.553982,0.000360
2,33,15,B,walk,Hallux,1.0,0.0,4091.917566,3320.376349,0.587162,0.001906
3,50,15,B,walk,Hallux,0.0,0.0,4091.895976,3310.167812,0.598013,0.001735
4,66,15,B,walk,Hallux,5.0,1.0,4093.874877,3303.437439,0.605036,0.000464
...,...,...,...,...,...,...,...,...,...,...,...
5691755,577516,3,B,stairs up,Heel_L,219.0,0.0,4095.000000,4091.120750,0.001316,0.000000
5691756,577533,3,B,stairs up,Heel_L,209.0,1.0,4092.275035,4094.091678,0.000208,0.001235
5691757,577550,3,B,stairs up,Heel_L,197.0,0.0,4093.725430,4092.575143,0.000651,0.000578
5691758,577566,3,B,stairs up,Heel_L,114.0,0.0,3774.555796,4094.120982,0.000402,0.193779


In [ ]:
# Step 2: Create the new columns for step index and gait cycles
all_foot_sensors_df['step_index'] = None
all_foot_sensors_df['left_gait_cycle'] = None
all_foot_sensors_df['right_gait_cycle'] = None

# Step 3: Assign a sequential index based on unique participant and time groups
# Sort by 'participant_id' and 'time' to ensure sequential order
all_foot_sensors_df.sort_values(by=['participant_id', 'time'], inplace=True)

# Use `groupby` with `cumcount` to assign a sequential step index for each participant and time combination
all_foot_sensors_df['step_index'] = all_foot_sensors_df.groupby(['participant_id', 'time']).ngroup()

# Step 5: Set the new index as 'participant_id', 'step_index', and 'sensor_location'
all_foot_sensors_df.set_index(['participant_id', 'step_index', 'sensor_location'], inplace=True)

# Step 6: Sort the DataFrame based on the new index
all_foot_sensors_df.sort_index(inplace=True)

print("Step indexing complete and DataFrame sorted.")


Step indexing complete and DataFrame sorted.


In [ ]:
all_foot_sensors_df

time task surface_type   Left  \
participant_id step_index sensor_location                                    
1              0          Arch                  0    B         walk  467.0   
                          Hallux                0    B         walk    4.0   
                          Heel_L                0    B         walk  206.0   
                          Heel_R                0    B         walk  277.0   
                          Met1                  0    B         walk    0.0   
...                                           ...  ...          ...    ...   
25             711469     Heel_R           619784    B         walk    1.0   
                          Met1             619784    B         walk  101.0   
                          Met3             619784    B         walk   73.0   
                          Met5             619784    B         walk  100.0   
                          Toes             619784    B         walk   35.0   

                                            Right   Right__raw    Left__raw  \
participant_id step_index sensor_location                                     
1              0          Arch              369.0  4092.000000  3744.202196   
                          Hallux              1.0  4092.101098  3640.394172   
                          Heel_L            341.0  3915.045439  4094.797804   
                          Heel_R            227.0  3880.629307  4091.966301   
                          Met1                0.0  4094.033699  3476.932601   
...                                           ...          ...          ...   
25             711469     Heel_R              4.0  3593.434783  4090.024845   
                          Met1              999.0  4079.074534  3255.602484   
                          Met3             1311.0  4082.248447  3749.000000   
                          Met5              460.0  4083.049689  3929.490683   
                          Toes              352.0  4085.925466  3749.273292   

                                           Left__norm  Right__norm  \
participant_id step_index sensor_location                            
1              0          Arch               0.270828     0.002240   
                          Hallux             0.328879     0.001227   
                          Heel_L             0.000116     0.177082   
                          Heel_R             0.001388     0.272826   
                          Met1               0.739245     0.003961   
...                                               ...          ...   
25             711469     Heel_R             0.002622     0.283590   
                          Met1               0.756125     0.005631   
                          Met3               0.147225     0.003209   
                          Met5               0.141042     0.006559   
                          Toes               0.890888     0.011348   

                                          left_gait_cycle right_gait_cycle  
participant_id step_index sensor_location                                   
1              0          Arch                       None             None  
                          Hallux                     None             None  
                          Heel_L                     None             None  
                          Heel_R                     None             None  
                          Met1                       None             None  
...                                                   ...              ...  
25             711469     Heel_R                     None             None  
                          Met1                       None             None  
                          Met3                       None             None  
                          Met5                       None             None  
                          Toes                       None             None  

[5691760 rows x 11 columns]

In [ ]:
all_heel_strike_insole_segments_list

[array([    0,    42,    79, ..., 34696, 34726, 34759]),
 array([    0,    40,    70, ..., 34833, 34865, 34896]),
 array([    0,    46,    80, ..., 38503, 38536, 38572]),
 array([    0,    43,    83, ..., 37361, 37396, 37434]),
 array([    0,    38,    78, ..., 39359, 39390, 39423]),
 array([    0,    44,    80, ..., 40829, 40862, 40899]),
 array([    0,    43,    83, ..., 36615, 36651, 36690]),
 array([    0,    40,    79, ..., 34659, 34697, 34725]),
 array([    0,    42,    79, ..., 37126, 37154, 37187]),
 array([    0,    37,    67, ..., 33366, 33396, 33431]),
 array([    0,    31,    63, ..., 30598, 30628, 30656]),
 array([    0,    36,    68, ..., 30639, 30666, 30699]),
 array([    0,    38,    70, ..., 31707, 31735, 31769]),
 array([    0,    40,    81, ..., 37193, 37228, 37263]),
 array([    0,    44,    71, ..., 36249, 36287, 36313]),
 array([    0,    41,    80, ..., 39636, 39671, 39704]),
 array([    0,    37,    76,   111,   147,   181,   218,   250,   284,
          316,   

In [ ]:
ppant_all_foot_sensors_df = []
all_foot_sensors_df = foot_sensors_df

for p in all_foot_sensors_df['participant_id'].unique():
    current_ppant_df = all_foot_sensors_df.loc[all_foot_sensors_df['participant_id'] == p]
    # current_ppant_df = current_ppant_df.loc[current_ppant_df['sensor_location'] == 'Arch']
    # current_ppant_df = current_ppant_df.reset_index(drop=True)
    ppant_all_foot_sensors_df.append(current_ppant_df)

In [ ]:
ppant_all_foot_sensors_df[0]

,time,participant_id,task,surface_type,sensor_location,Left,Right,Right__raw,Left__raw,Left__norm,Right__norm
204533,0,1,B,walk,Arch,467.0,369.0,4092.000000,3744.202196,0.270828,0.002240
126128,0,1,B,walk,Hallux,4.0,1.0,4092.101098,3640.394172,0.328879,0.001227
235895,0,1,B,walk,Heel_L,206.0,341.0,3915.045439,4094.797804,0.000116,0.177082
220214,0,1,B,walk,Heel_R,277.0,227.0,3880.629307,4091.966301,0.001388,0.272826
157490,0,1,B,walk,Met1,0.0,0.0,4094.033699,3476.932601,0.739245,0.003961
...,...,...,...,...,...,...,...,...,...,...,...
235894,581650,1,B,walk,Heel_R,3.0,195.0,3707.793750,4094.000000,0.000683,0.554221
173170,581650,1,B,walk,Met1,3.0,3.0,4093.037500,4093.981250,0.001120,0.004022
188851,581650,1,B,walk,Met3,3.0,340.0,4093.000000,3338.000000,0.697600,0.001314
204532,581650,1,B,walk,Met5,96.0,307.0,4094.981250,3618.700000,0.899044,0.000029


In [ ]:
for i, df in enumerate(ppant_all_foot_sensors_df):
    if not isinstance(df, pd.DataFrame):
        print(f"Error: Element at index {i} in ppant_all_foot_sensors_df is not a DataFrame.")
    else:
        # Reset index to ensure compatibility with start and end positions
        df = df.reset_index(drop=True)

        # Process right gait cycles using heel_strike_insole_segments
        if i < len(heel_strike_insole_segments):
            right_cycles = heel_strike_insole_segments[i]
            df.loc[:, 'right_gait_cycles'] = None  # Initialize the column
            for j, (start, end) in enumerate(right_cycles):
                if start < len(df) and end < len(df):  # Check bounds
                    df.loc[start:end, 'right_gait_cycles'] = j + 1

        # Process left gait cycles using heel_strike_insole_segments_left
        if i < len(heel_strike_insole_segments_left):
            left_cycles = heel_strike_insole_segments_left[i]
            df.loc[:, 'left_gait_cycles'] = None  # Initialize the column
            for j, (start, end) in enumerate(left_cycles):
                if start < len(df) and end < len(df):  # Check bounds
                    df.loc[start:end, 'left_gait_cycles'] = j + 1

        # Process all steps using all_heel_strike_insole_segments_list
        if i < len(all_heel_strike_insole_segments_list):
            all_steps = all_heel_strike_insole_segments_list[i]
            df.loc[:, 'all_steps'] = None  # Initialize the column

            # Loop through each step and fill from the current to the next step
            for j in range(len(all_steps) - 1):
                start, end = all_steps[j], all_steps[j + 1] - 1
                if start < len(df) and end < len(df):  # Check bounds
                    df.loc[start:end, 'all_steps'] = j + 1

            # Fill the last step to the end of the DataFrame
            last_step = all_steps[-1]
            if last_step < len(df):
                df.loc[last_step:, 'all_steps'] = len(all_steps)

        # Save updated DataFrame back to the list
        ppant_all_foot_sensors_df[i] = df


In [ ]:
# ppant_all_foot_sensors_df[2]

In [ ]:
# plot_8_Hallux = all_foot_sensors_df[all_foot_sensors_df['participant_id'] == 8] & all_foot_sensors_df[all_foot_sensors_df['sensor_location'] == 'Hallux']

In [ ]:
# merge all the ppant_all_foot_sensors_df together
all_foot_sensors_df = pd.concat(ppant_all_foot_sensors_df)

In [ ]:
# all_foot_sensors_df

In [ ]:
# export csv to folder
all_foot_sensors_df.to_csv('/content/drive/MyDrive/Next_Step/Honda_Participants/CourseB/foot_pressure_data/all_foot_sensors_df.csv', index=False)

In [ ]:
# export csv to folder
all_foot_sensor_extras_df.to_csv('/content/drive/MyDrive/Next_Step/Honda_Participants/CourseB/foot_pressure_data/all_foot_sensor_extras_df.csv', index=False)